-- MCCIA Intern OS — seed users (run after schema.sql)
--
-- Recreates the four accounts that existed before the Neon → Supabase move.
-- Login is email-only, so no passwords here. Ids are generated by the database.
-- Re-runnable: `on conflict (email) do nothing` skips any that already exist.
--
-- Keep these emails in sync with src/auth/users.ts (display names/emojis/roles).

insert into public.users (email, name, role) values
  ('sujal@mcciapune.com',   'Sujal',    'admin'),
  ('pratik@mcciapune.com',  'Pratik',   null),
  ('intern1@mcciapune.com', 'Intern 1', null),
  ('intern2@mcciapune.com', 'Intern 2', null)
on conflict (email) do nothing;
